# Generated by Django 5.2.6 on 2025-11-06 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom_user', models.CharField(max_length=100, verbose_name='Prénom')),
                ('cin_user', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Le CIN doit contenir exactement 8 chiffres.', regex='^\\d{8}$')], verbose_name='CIN')),
                ('email_user', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('mdp', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('sexe_user', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('DateNaissance', models.DateField(verbose_name='Date de naissance')),
                ('telephone_user', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 8 chiffres.', regex='^\\d{8}$')], verbose_name='Téléphone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('institution', models.CharField(choices=[('DonVia Tunis Nord (El Menzah)', 'DonVia Tunis Nord (El Menzah)'), ('DonVia Tunis Centre Bab Bhar', 'DonVia Tunis Centre Bab Bhar)'), ('DonVia Tunis Sud Ibn Khaldoun', 'DonVia Tunis Sud Ibn Khaldoun'), ('DonVia Ariana Ville', 'DonVia Ariana Ville'), ('DonVia Ben Arous Centre', 'DonVia Ben Arous Centre'), ('DonVia Manouba Douar Hicher', 'DonVia Manouba Douar Hicher'), ('DonVia Nabeul Ville', 'DonVia Nabeul Ville'), ('DonVia Sousse Riadh', 'DonVia Sousse Riadh'), ('DonVia Sfax Ville', 'DonVia Sfax Ville'), ('DonVia Kairouan Médina', 'DonVia Kairouan Médina'), ('DonVia Bizerte Ville', 'DonVia Bizerte Ville'), ('DonVia Gabès Ville', 'DonVia Gabès Ville'), ('DonVia Mimédenine Ville', 'DonVia Médenine Ville'), ('DonVia Tataouine Ville', 'DonVia Tataouine Ville'), ('DonVia Tozeur Centre', 'DonVia Tozeur Centre'), ('DonVia Gafsa Ville', 'DonVia Gafsa Ville'), ('DonVia Sidi Bouzid Ville', 'DonVia Sidi Bouzid Ville'), ('DonVia Kasserine Ville', 'DonVia Kasserine Ville'), ('DonVia Siliana Ville', 'DonVia Siliana Ville'), ('DonVia Béja Nord', 'DonVia Béja Nord'), ('DonVia Jendouba Ville', 'DonVia Jendouba Ville'), ('DonVia Le Kef Ville', 'DonVia Le Kef Ville'), ('DonVia Mahdia Ville', 'DonVia Mahdia Ville'), ('DonVia Zaghouan Ville', 'DonVia Zaghouan Ville'), ('DonVia Monastir Ville', 'DonVia Monastir Ville')], max_length=100, verbose_name='Institution')),
                ('justificatifs', models.FileField(upload_to='demandeurs/justificatifs/', verbose_name='Documents justificatifs')),
                ('date_inscription_user', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('role', models.CharField(default='Demandeur', max_length=50, verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Demandeur',
                'verbose_name_plural': 'Demandeurs',
                'ordering': ['-date_inscription_user'],
            },
        ),
    ]
