# Generated by Django 5.2.7 on 2025-11-03 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=120)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('disponibilite', models.CharField(blank=True, choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('soir', 'Soir'), ('weekend', 'Week-end'), ('tous_les_jours', 'Tous les jours')], max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers/')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
