# Generated by Django 5.2.7 on 2025-10-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sang',
            fields=[
                ('id_sang', models.AutoField(primary_key=True, serialize=False)),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('rhesus', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
                ('quantite', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantité de sang en litres (ex: 0.50)', max_digits=4)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Distribué', 'Distribué'), ('Réservé', 'Réservé')], max_length=50)),
                ('date_collecte', models.DateField()),
                ('date_expiration', models.DateField()),
                ('lieu_stockage', models.CharField(max_length=100)),
            ],
        ),
    ]
