# Generated by Django 5.2.7 on 2025-10-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionSang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sang',
            name='type_don',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Sang total', 'Sang total'), ('Plaquettes', 'Plaquettes')], default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sang',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
    ]
