# Generated by Django 5.2.7 on 2025-11-11 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDoneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
