# Generated by Django 5.2.8 on 2025-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDoneurs', '0002_blooddonation_age_blooddonation_date_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='age',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refuseddonation',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refuseddonation',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
