# Generated by Django 5.2.7 on 2025-10-29 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres', regex='^[A-Za-z]+$')])),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nb_participants', models.IntegerField()),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Prévu', 'Prévu')], max_length=50)),
                ('lieu_evenement', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
