# Generated by Django 5.2.7 on 2025-10-29 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, message='La description doit contenir au moins 30 caractères.')]),
        ),
    ]
