# Generated by Django 5.2.7 on 2025-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvenements', '0002_alter_evenement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
