# Generated by Django 5.2.7 on 2025-11-11 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvenements', '0003_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres, chiffres, espaces, apostrophes ou tirets', regex="^[A-Za-zÀ-ÖØ-öø-ÿ0-9\\s'\\-]+$")]),
        ),
    ]
